# Generated by Django 5.1.3 on 2024-12-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_otpcode_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='accounts/default.jpg', upload_to='accounts/'),
        ),
    ]
