# Generated by Django 5.1.3 on 2025-01-12 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='code',
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='email',
        ),
    ]
