# Generated by Django 5.1.3 on 2025-01-17 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_otpcode_code_remove_otpcode_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPCode',
        ),
    ]
