version: '1.0'

services:
  web:
    build: ./
    command: gunicorn store.wsgi:application --bind 0.0.0.0:8000 --workers=3 --timeout=120
    volumes:
      - ./:/usr/src/app/  
      - static_volume:/usr/src/app/static/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - web

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mohammad
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=test
    networks:
      - web

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_NODE_IP_ADDRESS=0.0.0.0
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE=my_queue
    networks:
      - web
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - web
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static/
      # - ./frontend/:/usr/src/app/frontend/
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - web

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:80"
  #   networks:
  #     - web

volumes:
  postgres_data:
  static_volume:

networks:
  web:
