version: '1.0'

services:
  web:
    build: ./
    command: gunicorn store.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/  
      - static_volume:/usr/src/app/static/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mohammad
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=test

    # rabbitmq:
    #   hostname: rabbitmq
    #   image: rabbitmq:3-management
    #   ports:
    #     - 5672:5672
    #     - 15672:15672
    #   # env_file:
    #   #   - rabbitmq/.env
    #   environment:
    #     - RABBITMQ_NODE_IP_ADDRESS=0.0.0.0
    #     - RABBITMQ_DEFAULT_USER=myuser
    #     - RABBITMQ_DEFAULT_PASS=mypassword
    #     - RABBITMQ_HOST=rabbitmq
    #     - RABBITMQ_PORT=5672
    #     - RABBITMQ_QUEUE=my_queue
  
  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   environment:
  #     - REDIS_USER=myuser
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static/
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:

  # react:
  #   build:
  #   context: ./M102_front/M102_Final
  #   volumes:
  #   - react:/react
  #   - react_build:/react/dist
