version: '1.0'

services:
  web:
    build: ./
    command: gunicorn store.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mohammad
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=test
  
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

  # react:
  #   build:
  #   context: ./M102_front/M102_Final
  #   volumes:
  #   - react:/react
  #   - react_build:/react/dist

volumes:
  postgres_data: