version: '1.0'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    # env_file:
    #   - ./.env.dev

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mohammad
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=test

volumes:
  postgres_data: