# Generated by Django 5.1.3 on 2024-12-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_category_photo_url_remove_product_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_photo',
            field=models.ImageField(default='categories/default.jpg', upload_to='categories/'),
        ),
    ]
