# Generated by Django 5.1.3 on 2024-12-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_category_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_photo',
        ),
    ]
