# Generated by Django 5.1.3 on 2024-12-24 12:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_coupon_remove_discount_discount_type_and_more'),
        ('product', '0005_category_category_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='attributes',
            name='product',
            field=models.ManyToManyField(related_name='attributes', to='product.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='course_time',
            field=models.TimeField(default='12:20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='prerequisite',
            field=models.CharField(default='no', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='teacher',
            field=models.CharField(default='ali', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_photo',
            field=models.URLField(blank=True, default='https://127.0.0.1/media/categories/default.jpg', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='discount.discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_movie', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('product_photo', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_file', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('product_movie', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('product_photo', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_file', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
