# Generated by Django 5.1.3 on 2024-12-24 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_brand_remove_product_product_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_photo',
            field=models.URLField(blank=True, default='file:///home/mohammad/Desktop/store/media/accounts/default.jpg', null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
