# Generated by Django 5.1.3 on 2024-12-24 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_category_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_photo',
            field=models.URLField(blank=True, default='https://drive.google.com/uc?id=1U2mtE4jrTOfAfoZ4MO5iF8kkTP2aiohj', null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
