# Generated by Django 5.1.3 on 2024-12-24 10:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_category_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_photo',
            field=cloudinary.models.CloudinaryField(default='default_gseslf', max_length=255, verbose_name='image'),
        ),
    ]
