# Generated by Django 5.1.3 on 2025-01-08 03:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_category_category_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicfile',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='topicfile',
            old_name='product_movie',
            new_name='topic_photo',
        ),
        migrations.RemoveField(
            model_name='topicfile',
            name='product_photo',
        ),
        migrations.CreateModel(
            name='TopicMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('topic_movie', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('topic_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_media', to='product.topicfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
