# Generated by Django 5.1.3 on 2024-12-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
