FROM nginx:alpine3.20-slim
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/

# کپی فایل‌های استاتیک Django
# COPY ../static/ /usr/src/app/static/

# کپی خروجی build از React
# COPY ../frontend/ /usr/src/app/frontend/
