# Generated by Django 5.1.3 on 2024-12-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('T', 'Teacher'), ('S', 'Student')], max_length=50)),
                ('message', models.TextField(max_length=5000)),
                ('resume', models.FileField(upload_to='contact_us/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
