# Generated by Django 5.1.3 on 2024-12-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='full_name',
            new_name='name',
        ),
    ]
